services:
  app:
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # Evita sujeira de cache .pyc na sua pasta local
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none # Desliga completamente o monitoramento de arquivos, liberando a CPU.
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false # Desativa a coleta de métricas do Streamlit, deixando a inicialização mais leve.
    volumes:
      - .:/app # Mapeia todo o seu código atual para dentro do container
      - /app/__pycache__ # Cria um volume anônimo para o cache do container não conflitar com o local
    ports:
      - "8501:8501"

  extrator:
    build: .
    volumes:
      - .:/app # Permite que alterações no extrator reflitam sem rebuild também
      - /app/__pycache__
    command: python main.py 2024 2026
    restart: "no"