name: Deploy - Automação TCE

on:
  push:
    branches:
      - main

jobs:
  deploy_producao:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy Produção
        run: |
          set -x
          echo "=== 🚀 Iniciando deploy ==="

          cd "/home/administrador/Área de Trabalho/Projeto_Automacao/automacao_api_tse" || exit 1

          git fetch origin
          git checkout main
          git pull origin main

          echo "📦 Build e deploy Docker..."
          docker compose up -d --build --remove-orphans

          docker image prune -af
          docker builder prune -af
          docker container prune -f

          echo "✅ Deploy finalizado!"